dataset: cifar100
data_dir: ./data
stu_model: resnet8x4
tea_model: resnet32x4
milestone:
  - 150
  - 180
  - 210
devices: 
  - 0
kd: kd
optimizer: SGD
alpha: 0.5
gamma: 0.1
scheduler: multistep
wandb: 0
temperature: 4
batch_size: 64
num_workers: 4
num_epochs: 240
lr: 0.1
weight_decay: 0.0005
momentum: 0.9
teacher_checkpoint: download_ckpts/cifar_teachers/resnet32x4_vanilla/ckpt_epoch_240.pth
seed: 42
outputs: outputs/cifar100/kd-rs32x4-rs8x4
rl: False
clipping_ratio: 0.2
c_epoch: 5
a_epoch: 5
decay_stragegy: cosine
resume: ''
warmup_epoch: 20
rl_epoch: 20
rl_balance: 1
aug_epoch: 40
