dataset: cifar100
data_dir: ./data
stu_model: resnet20
tea_model: resnet56
milestone:
  - 150
  - 180
  - 210
devices: 
  - 0
kd: crd
alpha: 0.1
beta: 0.9
dkd_alpha: 1
dkd_beta: 2
optimizer: SGD
gamma: 0.1
scheduler: multistep
wandb: 0
temperature: 4
batch_size: 64
num_workers: 4
num_epochs: 240
lr: 0.05
weight_decay: 0.0005
momentum: 0.9
teacher_checkpoint: download_ckpts/cifar_teachers/resnet56_vanilla/ckpt_epoch_240.pth
seed: 42
outputs: outputs/cifar100/rl-rs56-rs20
rl: True
clipping_ratio: 0.2
c_epoch: 5
a_epoch: 5
decay_stragegy: cosine
resume: ''
warmup_epoch: 2
rl_epoch: 2
rl_balance: 1
aug_epoch: 1

