dataset: cifar100
data_dir: ./data
stu_model: wrn_16_2
tea_model: wrn_40_2
milestone:
  - 150
  - 180
  - 210
devices: 
  - 0
kd: dkd
alpha: 0.1
beta: 0.9
gamma: 0.1
dkd_alpha: 1
dkd_beta: 2
optimizer: SGD
scheduler: multistep
wandb: 1
temperature: 4
batch_size: 64
num_workers: 4
num_epochs: 240
lr: 0.05
weight_decay: 0.0005
momentum: 0.9
teacher_checkpoint: download_ckpts/cifar_teachers/wrn_40_2_vanilla/ckpt_epoch_240.pth
seed: 42
outputs: outputs/cifar100/rl-wrn40_2-wrn16_2
rl: True
clipping_ratio: 0.2
c_epoch: 5
a_epoch: 5
decay_stragegy: cosine
resume: ''
warmup_epoch: 20
rl_epoch: 20
rl_balance: 1
aug_epoch: 20

